name: Run Testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Label of the container job
  runner-job:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.19, "1.20", 1.21, 1.22]
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 4

      - name: Start MongoDB 4.2
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 4.2

      - uses: niden/actions-memcached@v7

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Run Tests
        run: |
          go test -v -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4